version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    expose:
      - 8501
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8501/_stcore/health"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    command: >
      bash -c "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
